services:
  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxynet"
      #Entrypoints:
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      #Refirect to https
      #      - "--entrypoints.http.http.redirections.entrypoint.to.https"
      #      - "--entrypoints.http.http.redirections.entrypoint.scheme.https"
      #SSL Let's Encrypt:
      - "--entrypoints.https.http.tls.certResolver=le"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=tester@shevchenko.ru"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.dashboard.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$Htffi55j$$BZUpv/5d42IwxVDCPPRp71"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.containers/letsencrypt:/letsencrypt
  
  overseer.webapi:
    user: root
    image: overseer.webapi
    build:
      context: .
      dockerfile: src/WebAPI/Overseer.WebAPI/Dockerfile
    environment:
      - CONNECTIONSTRINGS__Database=Host=overseer.database;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      overseer.database:
        condition: service_healthy
      reverse-proxy:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapi.rule=Host(`${BACKEND_HOST}`)"

  overseer.webui:
    image: overseer.webui
    build:
      context: .
      dockerfile: src/WebUI/Overseer.WebUI/Dockerfile
    environment:
      - OverseerApi__BaseUri=http://overseer.webapi
    depends_on:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webui.rule=Host(`${FRONTEND_HOST}`)"
  
  overseer.database:
    image: postgres:latest
    container_name: overseer.database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  overseer.keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: overseer.keycloak
    command:
      - "start-dev"
      - "--import-realm"
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./imports:/opt/keycloak/data/import
    ports:
      - 18080:8080
  
  overseer.redis:
    image: redis:latest
    container_name: overseer.redis
    ports:
      - "6379:6379"
    volumes:
      - ./.containers/redis:/data